# Generated by Django 5.1.3 on 2024-12-31 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_api', '0006_remove_endocrinologist_patients_patient_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=50)),
                ('test_result', models.FloatField()),
                ('test_time', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bg_readings', to='auth_api.patient')),
            ],
        ),
    ]
