# Generated by Django 5.1.3 on 2025-01-04 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_api', '0006_remove_endocrinologist_patients_patient_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kft', models.FloatField()),
                ('lft', models.FloatField()),
                ('bmi', models.FloatField()),
                ('waist_size', models.FloatField()),
                ('weight', models.FloatField()),
                ('hba1c', models.JSONField(default=list)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_info', to='auth_api.patient')),
            ],
        ),
    ]
