# Generated by Django 5.1.3 on 2025-01-04 23:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0006_remove_endocrinologist_patients_patient_supervisor'),
        ('medical_info', '0002_medicalinfo_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalinfo',
            name='hba1c',
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HbA1cTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.FloatField()),
                ('q2', models.FloatField()),
                ('q3', models.FloatField()),
                ('q4', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HbA1c', to='auth_api.patient')),
            ],
        ),
    ]
