# Generated by Django 5.1.3 on 2025-01-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_info', '0003_remove_medicalinfo_hba1c_medicalinfo_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinfo',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
