# Generated by Django 5.1.3 on 2025-01-13 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0007_patient_status'),
        ('medical_info', '0004_alter_medicalinfo_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hba1ctable',
            name='year',
            field=models.PositiveIntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hba1ctable',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hba1c_records', to='auth_api.patient'),
        ),
        migrations.AlterField(
            model_name='hba1ctable',
            name='q1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hba1ctable',
            name='q2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hba1ctable',
            name='q3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hba1ctable',
            name='q4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='hba1ctable',
            unique_together={('patient', 'year')},
        ),
    ]
