# Generated by Django 5.1.3 on 2025-01-13 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0007_patient_status'),
        ('medical_info', '0005_hba1ctable_year_alter_hba1ctable_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hba1ctable',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HbA1c', to='auth_api.patient'),
        ),
    ]
