# Generated by Django 5.1.3 on 2025-01-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0007_patient_status'),
        ('medical_info', '0006_alter_hba1ctable_patient'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hba1ctable',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='hba1ctable',
            name='q1',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hba1ctable',
            name='q2',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hba1ctable',
            name='q3',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hba1ctable',
            name='q4',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='hba1ctable',
            constraint=models.UniqueConstraint(fields=('patient', 'year'), name='unique_patient_year'),
        ),
    ]
