# Generated by Django 5.1.3 on 2025-01-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_info', '0007_alter_hba1ctable_unique_together_alter_hba1ctable_q1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinfo',
            name='kft',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='lft',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
