# Generated by Django 5.1.3 on 2024-12-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_user_is_staff_user_is_superuser_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=None, null=True),
        ),
    ]
