# Generated by Django 5.1.3 on 2024-12-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0004_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='endocrinologist',
            name='patients',
            field=models.ManyToManyField(related_name='supervised_by', to='auth_api.patient'),
        ),
    ]
