# Generated by Django 5.1.3 on 2025-01-03 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_api', '0006_remove_endocrinologist_patients_patient_supervisor'),
        ('blood_glucose_records', '0002_alter_bgreading_test_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField()),
                ('s_pressure', models.FloatField()),
                ('d_pressure', models.FloatField()),
                ('bp_test_type', models.CharField(choices=[('resting', 'Resting'), ('active', 'Active')], max_length=20)),
                ('bg_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood_glucose_records.bgreading')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_logs', to='auth_api.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField()),
                ('exercise_type', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('calories_burned', models.FloatField()),
                ('bg_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood_glucose_records.bgreading')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_logs', to='auth_api.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField()),
                ('food_name', models.CharField(max_length=200)),
                ('serving_size', models.CharField(max_length=50)),
                ('meal_type', models.CharField(choices=[('lunch', 'Lunch'), ('dinner', 'Dinner'), ('breakfast', 'Breakfast'), ('snack', 'Snack')], max_length=15)),
                ('fat', models.FloatField()),
                ('protein', models.FloatField()),
                ('fiber', models.FloatField()),
                ('carbs', models.FloatField()),
                ('sugar', models.FloatField()),
                ('bg_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood_glucose_records.bgreading')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_logs', to='auth_api.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField()),
                ('medication_name', models.CharField(max_length=100)),
                ('dosage_value', models.FloatField()),
                ('dosage_unit', models.CharField(max_length=20)),
                ('bg_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood_glucose_records.bgreading')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_logs', to='auth_api.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
