# Generated by Django 5.1.3 on 2025-01-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselog',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
